### ISSUE TITLE
The algorithm throws an error when used within the graphic modeler

### ISSUE THREAD

**Issue by suricactus** [knwin/OpenTopography-DEM-Downloader-qgis-plugin#1]
The algorithm throws an error when used within the graphic modeler when the layer extent is calculated from a dynamic layer, e.g. model input.

This is due to processing plugin passing just the layer id, not the layer extent.

![image](https://user-images.githubusercontent.com/2820439/153726475-08e32cd2-b7f5-442a-87f8-d69075d9e3e5.png)

Attached a problematic example.
[opentopography_issue_1.zip](https://github.com/knwin/OpenTopography-DEM-Downloader-qgis-plugin/files/8054430/opentopography_issue_1.zip)

The error itself is:
```
Traceback (most recent call last):
File "/home/suricactus/.local/share/QGIS/QGIS3/profiles/default/python/plugins/opentopography/OpenTopography_DEMDownloader_algorithm.py", line 84, in processAlgorithm
epsg = extent.split(' ')[1]
IndexError: list index out of range

Error encountered while running OpenTopography DEM Downloader
Execution failed after 0.10 seconds
```

**Comment by knwin** [comment]
Instead of layer parameter, please use extent parameter (from input parameter list) from which you can select your layer to get layer extent.

**Comment by suricactus** [comment]
Hey, @knwin . Yes, I am aware I can use a "extent parameter", but this means I will have two separate arguments with the same value:
- extent parameter - it's sole purpose to satisfy the needs of your plugin.
- vector layer parameter - I need it in a more advanced layer algorithm anyway.

If you check how other QGIS algorithms that accept layer extent work in the modeler, you can observe that using the layer layer extent can be a "Vector Layer" or "Raster Layer" model input, as well as algorithm output that is a layer. 

The reason why it works for them is that they don't parse the input value with spaces as you do, but they use the QGIS processing API by calling `parameterAsExtentGeometry` and `parameterAsExtentCrs`, as I did in #2 .

While your solution might be a working workaround, it is not a solution, since it does not work in all cases.
