### ISSUE TITLE
"API Key Error: Please check your API key OR Cannot Access DEM" happening way too often

### ISSUE THREAD

**Issue by Serranowski** [knwin/OpenTopography-DEM-Downloader-qgis-plugin#4]
Hi.

I wanted to address to this issue as lately this is happening too often.

**Comment by knwin** [comment]
Dear JuanBreav,

Sorry to know that you have problem using the plugin.

It works at my side.
We need to narrow down what cause the problem.
If you have extra space or trim a letter when you copy API key. It could
not access the dem.

You can test if your API key is ok or not with the below html request. You
add your api key at the place of "YOUR_API_KEY" and copy the whole link,
paste into the address box of a browser and stike Enter kye. It should
download a small DEM. (ref:
https://opentopography.org/blog/introducing-api-keys-access-opentopography-global-datasets
)

https://portal.opentopography.org/API/globaldem?demtype=NASADEM&south=45&north=46&west=-122&east=-121&outputFormat=GTiff&API_Key=
*YOUR_API_KEY*

if you dont get a dem download via the above link then your API key is
incorrect/wrong (trimmed or extra space). If it works then we can check the
next step.

best
kyaw

**Comment by Serranowski** [comment]
Hi, Kyaw!

Thanks a lot for your thorough reply. I have tried your method and it does effectively download the raster DEM, so we can discard an error on the API key.

Might it be that the error appears in QGIS when the area of interest is too large? I believe I can see a pattern, in which trying to download raster files comprising rather big pieces of land (let's say the entirety of Canada) throw the aforementioned error.

**Comment by knwin** [comment]
Dear JuanBreav,

There is a limit posed by the OpenTopography site (I am not part of it). I
got information from them as follow
"
The limits are posted on our swagger docs: https://portal.opentopography
.org/apidocs/#/Public/getGlobalDem.  The limits are:

Requests are limited to 125,000,000 km2 for SRTM15+ V2.1, 4,050,000 km2 for
> SRTM GL3, COP90 and 450,000 km2 for all other data


"

They put this limit so as not to overload their server as far as I
understand.

Best,
Kyaw

**Comment by Squiglyman** [comment]
Dear Kyaw,

I am getting this same error message when I try do donwload a DEM from the QGIS plugin. I've used Opentopography DEM downloader many times in the past so I'm quite positive I'm following all the correct steps.

I get the following message "API Key Error: Please check your API key OR Cannot Access DEM"

I know that the key itself is working. The parcel of land is also not too large as I have asked a friend to run the same process and it works on his side. Any ideas what could cause the error?

Thanks in advance,
Dan

**Comment by knwin** [comment]
> Dear Kyaw,
> 
> I am getting this same error message when I try do donwload a DEM from the QGIS plugin. I've used Opentopography DEM downloader many times in the past so I'm quite positive I'm following all the correct steps.
> 
> I get the following message "API Key Error: Please check your API key OR Cannot Access DEM"
> 
> I know that the key itself is working. The parcel of land is also not too large as I have asked a friend to run the same process and it works on his side. Any ideas what could cause the error?
> 
> Thanks in advance, Dan

Dear Dan,
Could you please try outside of Qgis with your API keys. You can enter in a browser's address bar as mentioned in the site as follow..

https://portal.opentopography.org/API/globaldem?demtype=NASADEM&south=45&north=46&west=-122&east=-121&outputFormat=GTiff&API_Key=
*YOUR_API_KEY*

if you dont get a dem download via the above link then your API key is
incorrect/wrong (trimmed or extra space). If it works then we can check the
next step.

sorry my late response.

**Comment by Squiglyman** [comment]
Dear Kyaw,

Thank you for getting back to me! I can confirm my API key does work thanks. In the meantime I think I was able to figure out the issue. It seems that for some reason everything (all layers and project coordinate system) needs to be set to EPSG 4326 WGS 84 and then it runs?

Best regards,
Dan
