### ISSUE TITLE
EU_DTM data source request

### ISSUE THREAD

**Issue by kinotus** [knwin/OpenTopography-DEM-Downloader-qgis-plugin#5]
Hi,

OpenTopography also provides a global raster dataset called "EU_DTM", as described in https://portal.opentopography.org/apidocs/#/Public/getGlobalDem

Would it be possible to add support for downloading it with the plugin?

Thanks!

**Comment by kinotus** [comment]
Dataset link https://portal.opentopography.org/datasetMetadata?otCollectionID=OT.092022.3035.1

**Comment by knwin** [comment]
Thanks for the info. I will check and let you know.

**Comment by knwin** [comment]
Hi, I have added the two DEMs that you mentioned today. The official new version will be released soon. in the meantime, you can download it from here and test it.
