### ISSUE TITLE
Batch process: There was a Key error: PARAMETERS after uploading json file

### ISSUE THREAD

**Issue by Liyao89** [knwin/OpenTopography-DEM-Downloader-qgis-plugin#7]
Hi developer, thank you so much for developing this plugin tool and it's vey useful. I've met an issue during the batch process of data downloading.
I transferred the excel data to the json file, using the same index as the plugin.

![image](https://github.com/knwin/OpenTopography-DEM-Downloader-qgis-plugin/assets/165668130/64085585-58dc-4eae-8dc7-1a59950658f8)

But after uploading the json file, there was a Key error: PARAMETERS. 
What should I do to eliminate the error? Thank you so much for your time!

**Comment by knwin** [comment]
I have tested at my side. Batch processing is working fine.
Could you please check, if your plugin is latest version i.e ver-2.
In version 1, errors other than API keys are not shown detail. But in version-2 error message clearly indicate the cause of the problem. Some time you may ask very large area which is greater than what OpenTopgraphy site has permitted. Then you will be prompted with e.g "Error: The maximum area for SRTMGL3 is 4,050,000 km2. The selected area is 5xx,xxx,xxx km2." By looking at your extent coordinates, you are downloading DEMs on Atlantic Continent to which I am not sure your desire DEM type covers or not.
